### PR TITLE
Todo list refactor

### PR DESCRIPTION
**Pull request by bondgirl100**

### CODE REVIEW

**Comment by bondgirl100** [comment]
Resolves #38

**Review by ananyaahluwalia01 — CHANGES_REQUESTED** [review]
Looks awesome! I love the new feature. The bullet point unfortunately doesn't show up as a bullet point on my computer- it shows up as a diamond with a question mark in it. Maybe change change that to a dash or a more common symbol.

**Comment by bondgirl100** [comment]
Added the change!

**Review by ananyaahluwalia01 — CHANGES_REQUESTED** [review]
Perfect- another quick note: right now the date is getting cut off a bit because that line is a bit cluttered. Maybe move some things around/make the text line a bit shorter so everything is visible. Other than that- it all looks great!
image

**Comment by bondgirl100** [comment]
Awesome thanks - all done.

**Review by ananyaahluwalia01 — APPROVED** [review]
Looks awesome! Nice one Rachel

**Pull request merged**
